# Generated by Django 5.2.4 on 2025-08-04 21:45

import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_party_address_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractor',
            new_name='ContractorProfile',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeProfile',
        ),
        migrations.AlterField(
            model_name='party',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
    ]
