# Generated by Django 5.2.4 on 2025-08-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_contractor_contractorprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorprofile',
            old_name='profile',
            new_name='party',
        ),
    ]
