# Generated by Django 5.2.4 on 2025-08-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_rename_profile_contractorprofile_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='gender',
            field=models.CharField(default='male', max_length=8),
            preserve_default=False,
        ),
    ]
