# Generated by Django 5.2.4 on 2025-08-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_party_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='compensation_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('salaried', 'Salaried')], default='hourly'),
        ),
    ]
