# Generated by Django 5.2.4 on 2025-08-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeeprofile_compensation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorprofile',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
