# Generated by Django 5.2.4 on 2025-08-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_contractorprofile_contract_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default='-', upload_to='documents/_staging/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.party'),
            preserve_default=False,
        ),
    ]
