# Generated by Django 5.2.4 on 2025-08-18 01:07

import datetime
import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_document_owner_document_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorprofile',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contractorprofile',
            name='party',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='party',
        ),
        migrations.RemoveField(
            model_name='party',
            name='dependants',
        ),
        migrations.RemoveField(
            model_name='party',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='party',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='party',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='party',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='party',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='party',
            name='ssn',
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='TIN',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='contractor_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='party_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dependants',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced')], default='single', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='party_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.party'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ssn',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_hired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='party',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='address_full',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='address_state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('AK', 'Alaska')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='address_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
