# Generated by Django 5.2.4 on 2025-08-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_remove_contractorprofile_contract_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorprofile',
            old_name='TIN',
            new_name='tin',
        ),
    ]
